version: "3"

services:
  kumojin-backend:
    container_name: kumojin-backend-container
    image: node:14
    working_dir: /usr/src/kumojin
    restart: always
    command: bash -c "npm install && npm run start"
    volumes:
      - ./backend:/usr/src/kumojin/
    ports:
      - "3000:3000"
    network_mode: bridge

  kumojin-front:
    container_name: kumojin-front-container
    image: node:14
    working_dir: /usr/src/kumojin
    restart: always
    command: bash -c "npm install && npm run serve"
    volumes:
      - ./frontend:/usr/src/kumojin/
    ports:
      - "80:8080"
    depends_on:
      - kumojin-backend
    network_mode: bridge